version: '3.4'

volumes:
  ollama: {}

services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
    command: serve
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
